# Generated by Django 3.2.5 on 2021-07-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210718_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
